### ISSUE TITLE
Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms.

### ISSUE THREAD

**Issue by gagern** [gagern/selenium-chroot#1]
The initial version (as of @ac80f16b708838ce8bd44cd3439da8d7f456f5d9) fails with the following error message:

```
UnknownError: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms.
```

Looking at `strace` output, it seems as if the `java` process (presumably running Selenium code) is binding to that port, then trying to connect to it, without ever anyone listening to it. At some point, `strace` logs contain the following back trace:

```
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:

        at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:120)
        at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:275)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:116)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:222)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:215)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:133)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:85)
        at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:79)
        at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:62)
        at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
        at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

Not sure whether this will be of any use. The `/usr/lib/firefox/firefox -foreground` process apparently loads a bunch of libraries (presumably normal app startup) before getting stuck in some `futex`, waiting for I-don't-know-what.

**Comment by gagern** [comment]
Comparing a run with the problem described above against one based on the official repo, here is a diff of the `strace` from the firefox process:

``` diff
--- fakechroot
+++ selenium docker
@@ -1,33 +1,44 @@
-open("…/selenium-all/lib/x86_64-linux-gnu/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 3
+open("/lib/x86_64-linux-gnu/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 3
 read(3, "\177ELF…
 fstat(3, {st_mode=S_IFREG|0644, st_size=90080, ...}) = 0
+mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x…
 mmap(NULL, 2185952, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x…
 mprotect(0x…, 2093056, PROT_NONE) = 0
 mmap(0x…, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x15000) = 0x…
 close(3)                          = 0
 mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x…
 mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x…
 arch_prctl(ARCH_SET_FS, 0x…) = 0
 mprotect(0x…, 16384, PROT_READ) = 0
 mprotect(0x…, 4096, PROT_READ) = 0
 mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x…
 mprotect(0x…, 32768, PROT_READ) = 0
 mprotect(0x…, 4096, PROT_READ) = 0
 mprotect(0x…, 4096, PROT_READ) = 0
 mprotect(0x…, 4096, PROT_READ) = 0
 mprotect(0x…, 4096, PROT_READ) = 0
-mprotect(0x…, 4096, PROT_READ) = 0
-munmap(0x…, 15638)     = 0
-set_tid_address(0x…)   = 281
+munmap(0x…, 19106)     = 0
+set_tid_address(0x…)   = 113
 set_robust_list(0x…, 24) = 0
 futex(0x…, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 1, NULL, 7f…) = -1 EAGAIN (Resource temporarily unavailable)
 rt_sigaction(SIGRTMIN, {0x…, [], SA_RESTORER|SA_SIGINFO, 0x…}, NULL, 8) = 0
 rt_sigaction(SIGRT_1, {0x…, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x…}, NULL, 8) = 0
 rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
 getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
-getcwd("…/selenium-all", 4096) = 42
-futex(0x…, FUTEX_WAKE_PRIVATE, 2147483647) = 0
-futex(0x…, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
-<... futex resumed> )             = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
---- SIGTERM {si_signo=SIGTERM, si_code=SI_USER, si_pid=259, si_uid=0} ---
-+++ killed by SIGTERM +++
+getrusage(RUSAGE_SELF, {ru_utime={0, 2000}, ru_stime={0, 2000}, ...}) = 0
+lstat("/usr", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
+lstat("/usr/lib", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
+lstat("/usr/lib/firefox", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
+lstat("/usr/lib/firefox/firefox", {st_mode=S_IFREG|0755, st_size=112848, ...}) = 0
+stat("/usr/lib/firefox/firefox", {st_mode=S_IFREG|0755, st_size=112848, ...}) = 0
+access("/usr/lib/firefox/libxul.so", R_OK) = 0
+mmap(NULL, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0
+munmap(0x…, 1048576)   = 0
+mmap(NULL, 2093056, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0
+munmap(0x…, 798720)    = 0
+munmap(0x…, 245760)    = 0
+mmap(NULL, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0
+munmap(0x…, 1048576)   = 0
+mmap(NULL, 2093056, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0
+munmap(0x…, 1044480)   = 0
+open("/usr/lib/firefox/dependentlibs.list", O_RDONLY) = 3
```

Does that mean that the codepath that usually should lead to the `getrusage` call somehow got sidetracked, to call `getcwd` and then enter some dead-lock? Even with https://mxr.mozilla.org/ it's hard to associate the above to the Firefox code base.

**Comment by gagern** [comment]
I installed `gdb` and got a stack trace:

```
#0 in __lll_lock_wait () from …/selenium-all/lib/x86_64-linux-gnu/libpthread.so.0
#1 in _L_lock_1082 () from …/selenium-all/lib/x86_64-linux-gnu/libpthread.so.0
#2 in pthread_mutex_lock () from …/selenium-all/lib/x86_64-linux-gnu/libpthread.so.0
#3 in ?? ()
#4 in calloc ()
#5 in ?? () from …/selenium-all/lib/x86_64-linux-gnu/libdl.so.2
#6 in dlsym () from …/selenium-all/lib/x86_64-linux-gnu/libdl.so.2
#7 in ?? () from /usr/lib/x86_64-linux-gnu/fakechroot/libfakechroot.so
#8  in readlink () from /usr/lib/x86_64-linux-gnu/fakechroot/libfakechroot.so
#9  in ?? ()
#10 in malloc ()
#11 in fakechroot_init () from /usr/lib/x86_64-linux-gnu/fakechroot/libfakechroot.so
#12 in call_init (…) at dl-init.c:78
#13 in call_init (…) at dl-init.c:36
#14 _dl_init (…) at dl-init.c:126
#15 in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#16 in ?? ()
#17 in ?? ()
#18 in ?? ()
#19 in ?? ()
```

So it seems that `libfakechroot` isn't fully initialized yet. Editing `usr/bin/firefox` to export `FAKECHROOT_DEBUG=1` I can see output for `readlink("/etc/malloc.conf", &buf, 4096)`. So apparently the `malloc` call causes the `readlink` at a point where the library isn't ready for it yet. I guess, I'll have to tweak `fakechroot`…

**Comment by gagern** [comment]
Solved https://github.com/dex4er/fakechroot/issues/31 using https://github.com/gagern/fakechroot/commit/355f946d245dd7d7e1b101ad4ee6629e821971c8 in https://github.com/gagern/selenium-chroot/commit/1374e8c92dc32a11c3453eeacb7f7c0d526b5c9f.
